steps:
  - label: ":docker: build images amd"
    command: "mkdir -p bin/ && docker build -f Dockerfile --platform linux/amd64,linux/arm64 -output ./bin"
    artifact_paths:
      - "bin/*"
    agents:
      queue: hosted-linux-amd
  # - label: ":docker: build images arm"
  #   command: "mkdir -p bin/ && docker build -f Dockerfile -output ./bin"
  #   artifact_paths:
  #     - "bin/*"
  #   agents:
  #     queue: hosted-linux-arm
